package com.ibt.ava.util

class Url {
    companion object {
        val IP_URL = "https://ipv4.icanhazip.com"
       // val BASE_IP_URL = "https://admin.ava.news/api/"
        val BASE_IP_URL = " https://api.ava.news/api/"
        val NEWS_API = "${BASE_IP_URL}news"
        val NEWS_CATEGORIES_API = "${BASE_IP_URL}news-categories"
        val HOME_NEWS_ENDPOINT= "${BASE_IP_URL}apphome"
        val NEWS_DETAILS_ENDPOINT= "${NEWS_API}/%s?full_content=true"
        val HOME_CURRENT_WEATHER_ENDPOINT= "${BASE_IP_URL}currentweather"
        val HOME_All_WEATHER_ENDPOINT= "${BASE_IP_URL}weather"
        val FEATURED_NEWS_ENDPOINT= "$NEWS_API?featured=true&limit=1"
        var MULTIMEDIA_VIDEO= BASE_IP_URL+"multimediavideos"
        var MULTIMEDIA_IMAGES= BASE_IP_URL+"multimediagallery"
        val API_KEY="51310ad0-c945-4761-9c4b-b9486ea7ba59"
        val WEATHER_ICON="https://openweathermap.org/img/wn/%s@4x.png"
        val LOGIN= BASE_IP_URL+"general-users/login"
        val LOGIN_SOCIAL= BASE_IP_URL+"general-users/login/socialdatasubmit"
        val SIGNUP= BASE_IP_URL+"general-users/register"
        val VerifyOtp= BASE_IP_URL+"general-users/verify-otp"
        val PROFILE= BASE_IP_URL+"general-users/me"
        val LOGOUT= BASE_IP_URL+"general-users/logout"
        val DELETE_ACCOUNT= BASE_IP_URL+"general-users/delete-account"
        val FORGOT_PASSWORD= BASE_IP_URL+"general-users/forgot-password"
        val RESET_PASSWORD= BASE_IP_URL+"general-users/reset-password"
        val VERIFY_FORGOT_PASSWORD_OTP= BASE_IP_URL+"general-users/verify-forgot-password-otp"
        val REGENERATE_OTP= BASE_IP_URL+"general-users/regenerate-otp"
        val UPDATE= BASE_IP_URL+"general-users/update-profile/%s"


        val BOOKMARK= BASE_IP_URL+"bookmarks"
        val BOOKMARKS_BY_USER= BASE_IP_URL+"bookmarks/user/%s"
        val BOOKMARK_UPDATE_OR_DELETE= BASE_IP_URL+"bookmarks/%s"
        val BOOKMARK_DELETE= BASE_IP_URL+"bookmarks/deletenews/%s"
        val BOOKMARKED= BASE_IP_URL+"bookmarks/isnewsbookmarked/%s"
        val BOOKMARKE_DELETE_ALL= BASE_IP_URL+"bookmarks/deleteall/%s"
        val AUTHOR_FOLLOW= BASE_IP_URL+"follow/%s"
        val AUTHOR_UNFOLLOW= BASE_IP_URL+"unfollow/%s"
        val AUTHOR_FOLLOW_LIST= BASE_IP_URL+"following/%s"
        val AUTHOR_FOLLOWED= BASE_IP_URL+"isauthorfollowed/%s"
        val STORIES= BASE_IP_URL+"stories"
        val NOTIFICATIONS= BASE_IP_URL+"notifications"
        val CHANNELS_BY_PODCAST= BASE_IP_URL+"podcasts-channels/%s"
        val ALL_PODCASTS= BASE_IP_URL+"podcasts-channels"
        val SEARCH= BASE_IP_URL+"search"
    }
}